package com.teeoda.memorytraining.global.GreenDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRAINING_HISTORY".
 */
public class TrainingHistory {

    private Long id;
    private String type;
    private Integer total;
    private Integer correctNum;
    private Integer timeSpent;
    private java.util.Date date;
    private Boolean isBest;

    public TrainingHistory() {
    }

    public TrainingHistory(Long id) {
        this.id = id;
    }

    public TrainingHistory(Long id, String type, Integer total, Integer correctNum, Integer timeSpent, java.util.Date date, Boolean isBest) {
        this.id = id;
        this.type = type;
        this.total = total;
        this.correctNum = correctNum;
        this.timeSpent = timeSpent;
        this.date = date;
        this.isBest = isBest;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Integer getCorrectNum() {
        return correctNum;
    }

    public void setCorrectNum(Integer correctNum) {
        this.correctNum = correctNum;
    }

    public Integer getTimeSpent() {
        return timeSpent;
    }

    public void setTimeSpent(Integer timeSpent) {
        this.timeSpent = timeSpent;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Boolean getIsBest() {
        return isBest;
    }

    public void setIsBest(Boolean isBest) {
        this.isBest = isBest;
    }

}
